// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: proto/user.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface User {
  id: number;
  vang: number;
  sucManh: number;
  auth_id: number;
}

export interface RegisterRequest {
  id: number;
}

export interface RegisterResponse {
  success: boolean;
}

export interface GetUserRequest {
  id: number;
}

export interface UserResponse {
  user: User | undefined;
}

export interface SaveGameRequest {
  user: User | undefined;
}

export interface SaveGameResponse {
  message: string;
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  register(request: RegisterRequest, metadata?: Metadata): Observable<RegisterResponse>;

  getProfile(request: GetUserRequest, metadata?: Metadata): Observable<UserResponse>;

  saveGame(request: SaveGameRequest, metadata?: Metadata): Observable<SaveGameResponse>;
}

export interface UserServiceController {
  register(request: RegisterRequest, metadata?: Metadata): Observable<RegisterResponse>;

  getProfile(request: GetUserRequest, metadata?: Metadata): Observable<UserResponse>;

  saveGame(request: SaveGameRequest, metadata?: Metadata): Observable<SaveGameResponse>;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["register", "getProfile", "saveGame"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
